# Generated by Django 5.1 on 2024-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
